
server:
  port: 8090

spring:
  application:
    name: rpc-server

myrpc:
  server:
    address: 127.0.0.1:9000
  registry:
    address: 47.108.208.206:2181
    root-path: /registry
  serializer:
    type: protostuff
