
server:
  port: 8091

spring:
  application:
    name: rpc-client

myrpc:
  registry:
    address: 47.108.208.206:2181
    root-path: /registry
  serializer:
    type: protostuff
  loadbalance:
    type: com.pai.rpc.loadbalance.impl.ConsistentHashLoadBalance
    #type: com.pai.rpc.loadbalance.impl.RoundRobinLoadBalance